{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mobility-finance.serviceAccountName" . }}
  labels:
    {{- include "mobility-finance.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if .Values.serviceAccount.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ required "workload identity clientId is required" .Values.serviceAccount.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ required "workload identity tenantId is required" .Values.serviceAccount.workloadIdentity.tenantId | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.workloadIdentity.enabled }}
{{- end }}
