<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/MobilityFinance.Contracts/MobilityFinance.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/MobilityFinance.ServiceDefaults/MobilityFinance.ServiceDefaults.csproj" />
    <ProjectReference Include="../MobilityFinance.Ledger.Domain/MobilityFinance.Ledger.Domain.csproj" />
  </ItemGroup>

</Project>
