<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/MobilityFinance.Contracts/MobilityFinance.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/MobilityFinance.Messaging/MobilityFinance.Messaging.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/MobilityFinance.ServiceDefaults/MobilityFinance.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
