@MobilityFinance.Origination.Api_HostAddress = http://localhost:5151

GET {{MobilityFinance.Origination.Api_HostAddress}}/health/ready
Accept: application/json

###

GET {{MobilityFinance.Origination.Api_HostAddress}}/_system
Accept: application/json
